### ISSUE TITLE
Import CSV to SQL users table.

### ISSUE THREAD

**Issue by malmalakh** [mgp25/WhatsApp-Web-Client#11]
dear @mgp25 ... many thanks for the code ... since I have the phone number, phone password and phone ID, and I am trying to import the records to sql using csv file, could you please explain which refer to what:

id = ? ... is it an auto generated sequence?
phone = ? ... phone number without (+) or (00)?
login = ? ... user name?
password = ? ... phone password (or) user password?

**Comment by mgp25** [comment]
Its explained in the commented lines.

You can also find more information here: https://github.com/mgp25/WhatsAPI-Official/wiki
